name: Update Google Scholar Publications

on:
  workflow_dispatch:        # sadece elle tetikleme
  # schedule:
  #   - cron: "0 5 * * 1"   # (KAPATILDI) Haftalık auto-run, Scholar rate-limit’e takılabiliyor

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Ensure folders exist
        run: |
          mkdir -p tools assets/data

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly tenacity

      - name: Run scholar script
        env:
          SCHOLAR_ID: ${{ secrets.SCHOLAR_ID }}
        run: |
          python tools/update_scholar.py \
            --max 120 \
            --out assets/data/scholar_stats.json \
            --quiet

      - name: Commit and push if changed
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add assets/data/scholar_stats.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update publications from Google Scholar [skip ci]"
            git push
          else
            echo "No changes."
          fi
